### ISSUE TITLE
ICD list

### ISSUE THREAD

**Issue by tiagoantao** [conda-forge/pyopencl-feedstock#22]
The build recipe of pyopencl points to an ICD directory list on
$PREFIX/etc/OpenCL/vendors

But nothing populates that directory, as far as I know. I think that either:

1. It could point to /etc/OpenCL/vendors , though that would create a dependency on the OS

2. Users should be informed that they need to take action (e..g copy ICDs from /etc/OpenCL/vendors). I.e. some documentation should be provided elsewhere

3. There needs to be conda packages of ICDs

**Comment by inducer** [comment]
> There needs to be conda packages of ICDs

https://github.com/conda-forge/pocl-feedstock

> It could point to /etc/OpenCL/vendors , though that would create a dependency on the OS

This is perhaps more for https://github.com/conda-forge/ocl-icd-feedstock, but what I would *like* to happen is ocl-icd to search both the conda-specific location *and* the system-wide one. Patching that in seemed harder than I had time for, so that's not yet done.

> I.e. some documentation should be provided elsewhere

I completely agree, though I don't know of a good spot. This is where that documentation lives currently:

https://documen.tician.de/pyopencl/misc.html#installation

**Comment by tiagoantao** [comment]
You are totally right, this does not belong here. I will open it on pocl-feedstock. Makes more sense

**Comment by inducer** [comment]
I think you want https://github.com/conda-forge/ocl-icd-feedstock. :)
